# Personal AI Assistant - CI Workflow
# 持续集成：每次推送或 PR 时运行测试和代码检查
# Continuous Integration: Run tests and code checks on every push or PR

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  FLUTTER_VERSION: '3.24.0'

jobs:
  # ============================================
  # Backend CI - Python/FastAPI
  # ============================================
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Run mypy (type checking)
        run: uv run mypy app/

      - name: Run black (formatting check)
        run: uv run black --check app/

      - name: Run isort (import sorting check)
        run: uv run isort --check-only app/

      - name: Run flake8 (linting)
        run: uv run flake8 app/ --max-line-length=100 --extend-ignore=E203,W503

      - name: Run pytest
        run: uv run pytest -v --cov=app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.xml
          flags: backend
          name: backend-coverage

  # ============================================
  # Frontend CI - Flutter
  # ============================================
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [0, 1, 2]
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify dependencies
        run: flutter pub deps

      - name: Analyze code
        run: flutter analyze

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run tests (sharded)
        run: flutter test --coverage --test-randomize-ordering-seed random --shard-index=${{ matrix.shard }} --total-shards=3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage-shard-${{ matrix.shard }}

      - name: Check build (Web)
        run: flutter build web --no-sound-null-safety

  # ============================================
  # Desktop CI - Flutter Desktop
  # ============================================
  desktop-ci:
    name: Desktop CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos
    defaults:
      run:
        working-directory: frontend/desktop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build libgtk-3-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Enable desktop platform
        run: |
          if [ "${{ matrix.platform }}" == "linux" ]; then
            flutter config --enable-linux-desktop
          elif [ "${{ matrix.platform }}" == "windows" ]; then
            flutter config --enable-windows-desktop
          elif [ "${{ matrix.platform }}" == "macos" ]; then
            flutter config --enable-macos-desktop
          fi
        shell: bash

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test
