"""initial

Revision ID: 001
Revises: 
Create Date: 2026-02-09 11:16:07.739311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at_desc', 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_resource', 'admin_audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_user_action', 'admin_audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_resource_type'), 'admin_audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_user_id'), 'admin_audit_logs', ['user_id'], unique=False)
    op.create_table('ai_model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('model_type', sa.String(length=20), nullable=False, comment='模型类型：transcription/text_generation'),
    sa.Column('api_url', sa.String(length=500), nullable=False, comment='API端点URL'),
    sa.Column('api_key', sa.String(length=1000), nullable=False, comment='API密钥（加密存储）'),
    sa.Column('api_key_encrypted', sa.Boolean(), nullable=True, comment='API密钥是否加密'),
    sa.Column('model_id', sa.String(length=200), nullable=False, comment='模型标识符'),
    sa.Column('provider', sa.String(length=100), nullable=False, comment='提供商：openai/siliconflow/custom等'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大令牌数'),
    sa.Column('temperature', sa.String(length=10), nullable=True, comment='温度参数'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True, comment='请求超时时间（秒）'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
    sa.Column('max_concurrent_requests', sa.Integer(), nullable=True, comment='最大并发请求数'),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True, comment='每分钟请求限制'),
    sa.Column('cost_per_input_token', sa.String(length=20), nullable=True, comment='每输入令牌成本'),
    sa.Column('cost_per_output_token', sa.String(length=20), nullable=True, comment='每输出令牌成本'),
    sa.Column('extra_config', sa.JSON(), nullable=True, comment='额外配置参数'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认模型'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否为系统预设模型'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级（数字越小优先级越高）'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('success_count', sa.Integer(), nullable=True, comment='成功次数'),
    sa.Column('error_count', sa.Integer(), nullable=True, comment='错误次数'),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True, comment='总令牌使用数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_type_active', 'ai_model_configs', ['model_type', 'is_active'], unique=False)
    op.create_index('idx_model_type_default', 'ai_model_configs', ['model_type', 'is_default'], unique=False)
    op.create_index('idx_provider_model', 'ai_model_configs', ['provider', 'model_id'], unique=False)
    op.create_index(op.f('ix_ai_model_configs_id'), 'ai_model_configs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_model_configs_name'), 'ai_model_configs', ['name'], unique=False)
    op.create_table('background_task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_queue_started', 'background_task_runs', ['queue_name', 'started_at'], unique=False)
    op.create_index('idx_task_status_started', 'background_task_runs', ['status', 'started_at'], unique=False)
    op.create_index(op.f('ix_background_task_runs_id'), 'background_task_runs', ['id'], unique=False)
    op.create_index(op.f('ix_background_task_runs_queue_name'), 'background_task_runs', ['queue_name'], unique=False)
    op.create_index(op.f('ix_background_task_runs_started_at'), 'background_task_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_background_task_runs_status'), 'background_task_runs', ['status'], unique=False)
    op.create_index(op.f('ix_background_task_runs_task_name'), 'background_task_runs', ['task_name'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_token', 'password_resets', ['email', 'token'], unique=False)
    op.create_index('idx_email_unused', 'password_resets', ['email', 'is_used'], unique=False)
    op.create_index('idx_password_reset_token_expires', 'password_resets', ['token', 'expires_at'], unique=False)
    op.create_index(op.f('ix_password_resets_email'), 'password_resets', ['email'], unique=False)
    op.create_index(op.f('ix_password_resets_id'), 'password_resets', ['id'], unique=False)
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_item_published_at', sa.DateTime(timezone=True), nullable=True, comment='Published timestamp of the latest item from this feed'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetch_interval', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_type', 'subscriptions', ['source_type'], unique=False)
    op.create_index('idx_source_url', 'subscriptions', ['source_url'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='Setting key'),
    sa.Column('value', sa.JSON(), nullable=True, comment='Setting value (JSON)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Setting description'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Setting category: general, audio, ai, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Updated at'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_user_sessions_token_expires', 'user_sessions', ['session_token', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index('idx_email_status', 'users', ['email', 'status'], unique=False)
    op.create_index('idx_username_status', 'users', ['username', 'status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('podcast_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('audio_duration', sa.Integer(), nullable=True),
    sa.Column('audio_file_size', sa.Integer(), nullable=True),
    sa.Column('transcript_url', sa.String(length=500), nullable=True),
    sa.Column('transcript_content', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('summary_version', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('item_link', sa.String(length=500), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_link')
    )
    op.create_index('idx_podcast_episode_image', 'podcast_episodes', ['image_url'], unique=False)
    op.create_index('idx_podcast_episodes_item_link', 'podcast_episodes', ['item_link'], unique=True)
    op.create_index('idx_podcast_published', 'podcast_episodes', ['published_at'], unique=False)
    op.create_index('idx_podcast_status', 'podcast_episodes', ['status'], unique=False)
    op.create_index('idx_podcast_subscription', 'podcast_episodes', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_podcast_episodes_id'), 'podcast_episodes', ['id'], unique=False)
    op.create_table('subscription_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_category', 'subscription_categories', ['user_id', 'name'], unique=False)
    op.create_index(op.f('ix_subscription_categories_id'), 'subscription_categories', ['id'], unique=False)
    op.create_table('subscription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bookmarked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookmarked', 'subscription_items', ['bookmarked'], unique=False)
    op.create_index('idx_published_at', 'subscription_items', ['published_at'], unique=False)
    op.create_index('idx_read_at', 'subscription_items', ['read_at'], unique=False)
    op.create_index('idx_subscription_external', 'subscription_items', ['subscription_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_subscription_items_id'), 'subscription_items', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('update_frequency', sa.String(length=10), nullable=True, comment='Update frequency type: HOURLY, DAILY, WEEKLY'),
    sa.Column('update_time', sa.String(length=5), nullable=True, comment='Update time in HH:MM format (24-hour)'),
    sa.Column('update_day_of_week', sa.Integer(), nullable=True, comment='Day of week for WEEKLY frequency (1=Monday, 7=Sunday)'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='User has archived this subscription'),
    sa.Column('is_pinned', sa.Boolean(), nullable=True, comment='User has pinned this subscription'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_archived', 'user_subscriptions', ['user_id', 'is_archived'], unique=False)
    op.create_index('idx_user_subscription', 'user_subscriptions', ['user_id', 'subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_table('podcast_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('conversation_turn', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['podcast_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_created', 'podcast_conversations', ['created_at'], unique=False)
    op.create_index('idx_conversation_episode', 'podcast_conversations', ['episode_id'], unique=False)
    op.create_index('idx_conversation_turn', 'podcast_conversations', ['episode_id', 'conversation_turn'], unique=False)
    op.create_index('idx_conversation_user', 'podcast_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_podcast_conversations_created_at'), 'podcast_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_podcast_conversations_id'), 'podcast_conversations', ['id'], unique=False)
    op.create_table('podcast_playback_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('is_playing', sa.Boolean(), nullable=True),
    sa.Column('playback_rate', sa.Float(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_episode_unique', 'podcast_playback_states', ['user_id', 'episode_id'], unique=True)
    op.create_index(op.f('ix_podcast_playback_states_id'), 'podcast_playback_states', ['id'], unique=False)
    op.create_table('subscription_category_mappings',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['subscription_categories.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'category_id')
    )
    op.create_table('transcription_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', 'cancelled', name='transcriptionstatus'), nullable=False),
    sa.Column('current_step', sa.Enum('not_started', 'downloading', 'converting', 'splitting', 'transcribing', 'merging', name='transcriptionstep'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('original_audio_url', sa.String(length=500), nullable=False),
    sa.Column('original_file_path', sa.String(length=1000), nullable=True),
    sa.Column('original_file_size', sa.Integer(), nullable=True),
    sa.Column('transcript_content', sa.Text(), nullable=True),
    sa.Column('transcript_word_count', sa.Integer(), nullable=True),
    sa.Column('transcript_duration', sa.Integer(), nullable=True),
    sa.Column('summary_content', sa.Text(), nullable=True),
    sa.Column('summary_model_used', sa.String(length=100), nullable=True),
    sa.Column('summary_word_count', sa.Integer(), nullable=True),
    sa.Column('summary_processing_time', sa.Float(), nullable=True),
    sa.Column('summary_error_message', sa.Text(), nullable=True),
    sa.Column('chunk_info', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('download_time', sa.Float(), nullable=True),
    sa.Column('conversion_time', sa.Float(), nullable=True),
    sa.Column('transcription_time', sa.Float(), nullable=True),
    sa.Column('chunk_size_mb', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id')
    )
    op.create_index('idx_transcription_created', 'transcription_tasks', ['created_at'], unique=False)
    op.create_index('idx_transcription_episode', 'transcription_tasks', ['episode_id'], unique=True)
    op.create_index('idx_transcription_status', 'transcription_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_transcription_tasks_id'), 'transcription_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcription_tasks_id'), table_name='transcription_tasks')
    op.drop_index('idx_transcription_status', table_name='transcription_tasks')
    op.drop_index('idx_transcription_episode', table_name='transcription_tasks')
    op.drop_index('idx_transcription_created', table_name='transcription_tasks')
    op.drop_table('transcription_tasks')
    op.drop_table('subscription_category_mappings')
    op.drop_index(op.f('ix_podcast_playback_states_id'), table_name='podcast_playback_states')
    op.drop_index('idx_user_episode_unique', table_name='podcast_playback_states')
    op.drop_table('podcast_playback_states')
    op.drop_index(op.f('ix_podcast_conversations_id'), table_name='podcast_conversations')
    op.drop_index(op.f('ix_podcast_conversations_created_at'), table_name='podcast_conversations')
    op.drop_index('idx_conversation_user', table_name='podcast_conversations')
    op.drop_index('idx_conversation_turn', table_name='podcast_conversations')
    op.drop_index('idx_conversation_episode', table_name='podcast_conversations')
    op.drop_index('idx_conversation_created', table_name='podcast_conversations')
    op.drop_table('podcast_conversations')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_index('idx_user_subscription', table_name='user_subscriptions')
    op.drop_index('idx_user_archived', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_subscription_items_id'), table_name='subscription_items')
    op.drop_index('idx_subscription_external', table_name='subscription_items')
    op.drop_index('idx_read_at', table_name='subscription_items')
    op.drop_index('idx_published_at', table_name='subscription_items')
    op.drop_index('idx_bookmarked', table_name='subscription_items')
    op.drop_table('subscription_items')
    op.drop_index(op.f('ix_subscription_categories_id'), table_name='subscription_categories')
    op.drop_index('idx_user_category', table_name='subscription_categories')
    op.drop_table('subscription_categories')
    op.drop_index(op.f('ix_podcast_episodes_id'), table_name='podcast_episodes')
    op.drop_index('idx_podcast_subscription', table_name='podcast_episodes')
    op.drop_index('idx_podcast_status', table_name='podcast_episodes')
    op.drop_index('idx_podcast_published', table_name='podcast_episodes')
    op.drop_index('idx_podcast_episodes_item_link', table_name='podcast_episodes')
    op.drop_index('idx_podcast_episode_image', table_name='podcast_episodes')
    op.drop_table('podcast_episodes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_username_status', table_name='users')
    op.drop_index('idx_email_status', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_user_sessions_token_expires', table_name='user_sessions')
    op.drop_index('idx_user_active', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index('idx_source_url', table_name='subscriptions')
    op.drop_index('idx_source_type', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_email'), table_name='password_resets')
    op.drop_index('idx_password_reset_token_expires', table_name='password_resets')
    op.drop_index('idx_email_unused', table_name='password_resets')
    op.drop_index('idx_email_token', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_background_task_runs_task_name'), table_name='background_task_runs')
    op.drop_index(op.f('ix_background_task_runs_status'), table_name='background_task_runs')
    op.drop_index(op.f('ix_background_task_runs_started_at'), table_name='background_task_runs')
    op.drop_index(op.f('ix_background_task_runs_queue_name'), table_name='background_task_runs')
    op.drop_index(op.f('ix_background_task_runs_id'), table_name='background_task_runs')
    op.drop_index('idx_task_status_started', table_name='background_task_runs')
    op.drop_index('idx_task_queue_started', table_name='background_task_runs')
    op.drop_table('background_task_runs')
    op.drop_index(op.f('ix_ai_model_configs_name'), table_name='ai_model_configs')
    op.drop_index(op.f('ix_ai_model_configs_id'), table_name='ai_model_configs')
    op.drop_index('idx_provider_model', table_name='ai_model_configs')
    op.drop_index('idx_model_type_default', table_name='ai_model_configs')
    op.drop_index('idx_model_type_active', table_name='ai_model_configs')
    op.drop_table('ai_model_configs')
    op.drop_index(op.f('ix_admin_audit_logs_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_resource_type'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_index('idx_user_action', table_name='admin_audit_logs')
    op.drop_index('idx_resource', table_name='admin_audit_logs')
    op.drop_index('idx_created_at_desc', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
