"""Add admin audit log table

Revision ID: 012_add_admin_audit_log_table
Revises: 011_remove_download_method
Create Date: 2026-01-11 12:08:39.690149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012_add_admin_audit_log'
down_revision: Union[str, Sequence[str], None] = '011_remove_download_method'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely drop indexes if they exist
    from sqlalchemy import text
    conn = op.get_bind()

    # Drop indexes with IF EXISTS to avoid errors
    indexes = [
        'idx_audit_resource',
        'idx_audit_status_created',
        'idx_audit_user_action',
        'ix_admin_audit_logs_created_at',
        'ix_admin_audit_logs_id'
    ]
    for idx in indexes:
        conn.execute(text(f"DROP INDEX IF EXISTS {idx}"))

    # Drop table if exists
    conn.execute(text("DROP TABLE IF EXISTS admin_audit_logs CASCADE"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='User who performed the action / 执行操作的用户ID'),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Action type: create/update/delete/test/refresh / 操作类型'),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Resource type: api_key/subscription/user / 资源类型'),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID of the affected resource / 受影响的资源ID'),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Name of the resource for display / 资源名称（用于显示）'),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Operation details / 操作详细信息'),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True, comment='Client IP address / 客户端IP地址'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True, comment='Client user agent / 客户端用户代理'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Operation status: success/failure / 操作状态'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Error message if failed / 错误信息'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Operation timestamp / 操作时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('admin_audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_user_action'), 'admin_audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('idx_audit_status_created'), 'admin_audit_logs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('idx_audit_resource'), 'admin_audit_logs', ['resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###
