"""Shared components used across domains.

This package currently exposes only actively used shared modules:
- schemas
- file validation utilities
"""

from .file_validation import (
    ALLOWED_AUDIO_TYPES,
    ALLOWED_DOCUMENT_TYPES,
    ALLOWED_IMAGE_TYPES,
    ALLOWED_VIDEO_TYPES,
    FileValidationError,
    get_allowed_types_for_media,
    sanitize_filename,
    validate_file_extension,
    validate_file_size,
    validate_file_upload,
    validate_mime_type,
)
from .schemas import (
    APIResponse,
    BaseSchema,
    ConversationBase,
    ConversationCreate,
    ConversationResponse,
    ConversationUpdate,
    ErrorResponse,
    ForgotPasswordRequest,
    MessageBase,
    MessageCreate,
    MessageResponse,
    PaginatedResponse,
    PaginationParams,
    PasswordResetResponse,
    ResetPasswordRequest,
    SubscriptionBase,
    SubscriptionCreate,
    SubscriptionResponse,
    SubscriptionUpdate,
    TimestampedSchema,
    Token,
    TokenData,
    UserBase,
    UserCreate,
    UserInDB,
    UserLogin,
    UserResponse,
    UserUpdate,
)


__all__ = [
    "BaseSchema",
    "TimestampedSchema",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "UserLogin",
    "Token",
    "TokenData",
    "APIResponse",
    "ErrorResponse",
    "SubscriptionBase",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "SubscriptionResponse",
    "MessageBase",
    "MessageCreate",
    "MessageResponse",
    "ConversationBase",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "PasswordResetResponse",
    "PaginationParams",
    "PaginatedResponse",
    "FileValidationError",
    "validate_file_size",
    "validate_file_extension",
    "validate_mime_type",
    "sanitize_filename",
    "validate_file_upload",
    "get_allowed_types_for_media",
    "ALLOWED_IMAGE_TYPES",
    "ALLOWED_AUDIO_TYPES",
    "ALLOWED_VIDEO_TYPES",
    "ALLOWED_DOCUMENT_TYPES",
]
