// Mocks generated by Mockito 5.4.6 from annotations
// in personal_ai_assistant/test/widget/podcast/podcast_player_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:personal_ai_assistant/features/podcast/data/models/podcast_conversation_model.dart'
    as _i6;
import 'package:personal_ai_assistant/features/podcast/data/models/podcast_episode_model.dart'
    as _i3;
import 'package:personal_ai_assistant/features/podcast/data/models/podcast_playback_model.dart'
    as _i4;
import 'package:personal_ai_assistant/features/podcast/data/models/podcast_subscription_model.dart'
    as _i2;
import 'package:personal_ai_assistant/features/podcast/data/models/podcast_transcription_model.dart'
    as _i5;
import 'package:personal_ai_assistant/features/podcast/data/models/schedule_config_model.dart'
    as _i7;
import 'package:personal_ai_assistant/features/podcast/data/repositories/podcast_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePodcastSubscriptionModel_0 extends _i1.SmartFake
    implements _i2.PodcastSubscriptionModel {
  _FakePodcastSubscriptionModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePodcastSubscriptionListResponse_1 extends _i1.SmartFake
    implements _i2.PodcastSubscriptionListResponse {
  _FakePodcastSubscriptionListResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeReparseResponse_2 extends _i1.SmartFake
    implements _i2.ReparseResponse {
  _FakeReparseResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePodcastFeedResponse_3 extends _i1.SmartFake
    implements _i3.PodcastFeedResponse {
  _FakePodcastFeedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePodcastEpisodeListResponse_4 extends _i1.SmartFake
    implements _i3.PodcastEpisodeListResponse {
  _FakePodcastEpisodeListResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePodcastEpisodeDetailResponse_5 extends _i1.SmartFake
    implements _i3.PodcastEpisodeDetailResponse {
  _FakePodcastEpisodeDetailResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePodcastPlaybackStateResponse_6 extends _i1.SmartFake
    implements _i4.PodcastPlaybackStateResponse {
  _FakePodcastPlaybackStateResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePodcastSummaryResponse_7 extends _i1.SmartFake
    implements _i4.PodcastSummaryResponse {
  _FakePodcastSummaryResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePodcastStatsResponse_8 extends _i1.SmartFake
    implements _i4.PodcastStatsResponse {
  _FakePodcastStatsResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePodcastTranscriptionResponse_9 extends _i1.SmartFake
    implements _i5.PodcastTranscriptionResponse {
  _FakePodcastTranscriptionResponse_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePodcastConversationHistoryResponse_10 extends _i1.SmartFake
    implements _i6.PodcastConversationHistoryResponse {
  _FakePodcastConversationHistoryResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePodcastConversationSendResponse_11 extends _i1.SmartFake
    implements _i6.PodcastConversationSendResponse {
  _FakePodcastConversationSendResponse_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakePodcastConversationClearResponse_12 extends _i1.SmartFake
    implements _i6.PodcastConversationClearResponse {
  _FakePodcastConversationClearResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeScheduleConfigResponse_13 extends _i1.SmartFake
    implements _i7.ScheduleConfigResponse {
  _FakeScheduleConfigResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PodcastRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPodcastRepository extends _i1.Mock implements _i8.PodcastRepository {
  MockPodcastRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.PodcastSubscriptionModel> addSubscription({
    required String? feedUrl,
    List<int>? categoryIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSubscription, [], {
              #feedUrl: feedUrl,
              #categoryIds: categoryIds,
            }),
            returnValue: _i9.Future<_i2.PodcastSubscriptionModel>.value(
              _FakePodcastSubscriptionModel_0(
                this,
                Invocation.method(#addSubscription, [], {
                  #feedUrl: feedUrl,
                  #categoryIds: categoryIds,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.PodcastSubscriptionModel>);

  @override
  _i9.Future<_i2.PodcastSubscriptionListResponse> listSubscriptions({
    int? page = 1,
    int? size = 20,
    int? categoryId,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listSubscriptions, [], {
              #page: page,
              #size: size,
              #categoryId: categoryId,
              #status: status,
            }),
            returnValue: _i9.Future<_i2.PodcastSubscriptionListResponse>.value(
              _FakePodcastSubscriptionListResponse_1(
                this,
                Invocation.method(#listSubscriptions, [], {
                  #page: page,
                  #size: size,
                  #categoryId: categoryId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.PodcastSubscriptionListResponse>);

  @override
  _i9.Future<_i2.PodcastSubscriptionModel> getSubscription(
    int? subscriptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscription, [subscriptionId]),
            returnValue: _i9.Future<_i2.PodcastSubscriptionModel>.value(
              _FakePodcastSubscriptionModel_0(
                this,
                Invocation.method(#getSubscription, [subscriptionId]),
              ),
            ),
          )
          as _i9.Future<_i2.PodcastSubscriptionModel>);

  @override
  _i9.Future<void> deleteSubscription(int? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubscription, [subscriptionId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> refreshSubscription(int? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSubscription, [subscriptionId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.ReparseResponse> reparseSubscription(
    int? subscriptionId,
    bool? forceAll,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reparseSubscription, [subscriptionId, forceAll]),
            returnValue: _i9.Future<_i2.ReparseResponse>.value(
              _FakeReparseResponse_2(
                this,
                Invocation.method(#reparseSubscription, [
                  subscriptionId,
                  forceAll,
                ]),
              ),
            ),
          )
          as _i9.Future<_i2.ReparseResponse>);

  @override
  _i9.Future<_i3.PodcastFeedResponse> getPodcastFeed({
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPodcastFeed, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i9.Future<_i3.PodcastFeedResponse>.value(
              _FakePodcastFeedResponse_3(
                this,
                Invocation.method(#getPodcastFeed, [], {
                  #page: page,
                  #pageSize: pageSize,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.PodcastFeedResponse>);

  @override
  _i9.Future<_i3.PodcastEpisodeListResponse> listEpisodes({
    int? subscriptionId,
    int? page = 1,
    int? size = 20,
    bool? hasSummary,
    bool? isPlayed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listEpisodes, [], {
              #subscriptionId: subscriptionId,
              #page: page,
              #size: size,
              #hasSummary: hasSummary,
              #isPlayed: isPlayed,
            }),
            returnValue: _i9.Future<_i3.PodcastEpisodeListResponse>.value(
              _FakePodcastEpisodeListResponse_4(
                this,
                Invocation.method(#listEpisodes, [], {
                  #subscriptionId: subscriptionId,
                  #page: page,
                  #size: size,
                  #hasSummary: hasSummary,
                  #isPlayed: isPlayed,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.PodcastEpisodeListResponse>);

  @override
  _i9.Future<_i3.PodcastEpisodeDetailResponse> getEpisode(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisode, [episodeId]),
            returnValue: _i9.Future<_i3.PodcastEpisodeDetailResponse>.value(
              _FakePodcastEpisodeDetailResponse_5(
                this,
                Invocation.method(#getEpisode, [episodeId]),
              ),
            ),
          )
          as _i9.Future<_i3.PodcastEpisodeDetailResponse>);

  @override
  _i9.Future<_i4.PodcastPlaybackStateResponse> updatePlaybackProgress({
    required int? episodeId,
    required int? position,
    required bool? isPlaying,
    double? playbackRate = 1.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlaybackProgress, [], {
              #episodeId: episodeId,
              #position: position,
              #isPlaying: isPlaying,
              #playbackRate: playbackRate,
            }),
            returnValue: _i9.Future<_i4.PodcastPlaybackStateResponse>.value(
              _FakePodcastPlaybackStateResponse_6(
                this,
                Invocation.method(#updatePlaybackProgress, [], {
                  #episodeId: episodeId,
                  #position: position,
                  #isPlaying: isPlaying,
                  #playbackRate: playbackRate,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.PodcastPlaybackStateResponse>);

  @override
  _i9.Future<_i4.PodcastPlaybackStateResponse> getPlaybackState(
    int? episodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackState, [episodeId]),
            returnValue: _i9.Future<_i4.PodcastPlaybackStateResponse>.value(
              _FakePodcastPlaybackStateResponse_6(
                this,
                Invocation.method(#getPlaybackState, [episodeId]),
              ),
            ),
          )
          as _i9.Future<_i4.PodcastPlaybackStateResponse>);

  @override
  _i9.Future<_i4.PodcastSummaryResponse> generateSummary({
    required int? episodeId,
    bool? forceRegenerate = false,
    bool? useTranscript,
    String? summaryModel,
    String? customPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateSummary, [], {
              #episodeId: episodeId,
              #forceRegenerate: forceRegenerate,
              #useTranscript: useTranscript,
              #summaryModel: summaryModel,
              #customPrompt: customPrompt,
            }),
            returnValue: _i9.Future<_i4.PodcastSummaryResponse>.value(
              _FakePodcastSummaryResponse_7(
                this,
                Invocation.method(#generateSummary, [], {
                  #episodeId: episodeId,
                  #forceRegenerate: forceRegenerate,
                  #useTranscript: useTranscript,
                  #summaryModel: summaryModel,
                  #customPrompt: customPrompt,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.PodcastSummaryResponse>);

  @override
  _i9.Future<List<_i4.SummaryModelInfo>> getSummaryModels() =>
      (super.noSuchMethod(
            Invocation.method(#getSummaryModels, []),
            returnValue: _i9.Future<List<_i4.SummaryModelInfo>>.value(
              <_i4.SummaryModelInfo>[],
            ),
          )
          as _i9.Future<List<_i4.SummaryModelInfo>>);

  @override
  _i9.Future<void> getPendingSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSummaries, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.PodcastEpisodeListResponse> searchPodcasts({
    required String? query,
    String? searchIn = 'all',
    int? page = 1,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchPodcasts, [], {
              #query: query,
              #searchIn: searchIn,
              #page: page,
              #size: size,
            }),
            returnValue: _i9.Future<_i3.PodcastEpisodeListResponse>.value(
              _FakePodcastEpisodeListResponse_4(
                this,
                Invocation.method(#searchPodcasts, [], {
                  #query: query,
                  #searchIn: searchIn,
                  #page: page,
                  #size: size,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.PodcastEpisodeListResponse>);

  @override
  _i9.Future<_i4.PodcastStatsResponse> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue: _i9.Future<_i4.PodcastStatsResponse>.value(
              _FakePodcastStatsResponse_8(
                this,
                Invocation.method(#getStats, []),
              ),
            ),
          )
          as _i9.Future<_i4.PodcastStatsResponse>);

  @override
  _i9.Future<void> getRecommendations({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendations, [], {#limit: limit}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.PodcastTranscriptionResponse?> getTranscription(
    int? episodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTranscription, [episodeId]),
            returnValue: _i9.Future<_i5.PodcastTranscriptionResponse?>.value(),
          )
          as _i9.Future<_i5.PodcastTranscriptionResponse?>);

  @override
  _i9.Future<_i5.PodcastTranscriptionResponse> startTranscription(
    int? episodeId, {
    bool? forceRegenerate = false,
    int? chunkSizeMb,
    String? transcriptionModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startTranscription,
              [episodeId],
              {
                #forceRegenerate: forceRegenerate,
                #chunkSizeMb: chunkSizeMb,
                #transcriptionModel: transcriptionModel,
              },
            ),
            returnValue: _i9.Future<_i5.PodcastTranscriptionResponse>.value(
              _FakePodcastTranscriptionResponse_9(
                this,
                Invocation.method(
                  #startTranscription,
                  [episodeId],
                  {
                    #forceRegenerate: forceRegenerate,
                    #chunkSizeMb: chunkSizeMb,
                    #transcriptionModel: transcriptionModel,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i5.PodcastTranscriptionResponse>);

  @override
  _i9.Future<void> deleteTranscription(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTranscription, [episodeId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.PodcastTranscriptionResponse?> getTranscriptionStatus(
    int? episodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTranscriptionStatus, [episodeId]),
            returnValue: _i9.Future<_i5.PodcastTranscriptionResponse?>.value(),
          )
          as _i9.Future<_i5.PodcastTranscriptionResponse?>);

  @override
  _i9.Future<_i6.PodcastConversationHistoryResponse> getConversationHistory({
    required int? episodeId,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationHistory, [], {
              #episodeId: episodeId,
              #limit: limit,
            }),
            returnValue:
                _i9.Future<_i6.PodcastConversationHistoryResponse>.value(
                  _FakePodcastConversationHistoryResponse_10(
                    this,
                    Invocation.method(#getConversationHistory, [], {
                      #episodeId: episodeId,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i6.PodcastConversationHistoryResponse>);

  @override
  _i9.Future<_i6.PodcastConversationSendResponse> sendConversationMessage({
    required int? episodeId,
    required _i6.PodcastConversationSendRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendConversationMessage, [], {
              #episodeId: episodeId,
              #request: request,
            }),
            returnValue: _i9.Future<_i6.PodcastConversationSendResponse>.value(
              _FakePodcastConversationSendResponse_11(
                this,
                Invocation.method(#sendConversationMessage, [], {
                  #episodeId: episodeId,
                  #request: request,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.PodcastConversationSendResponse>);

  @override
  _i9.Future<_i6.PodcastConversationClearResponse> clearConversationHistory({
    required int? episodeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearConversationHistory, [], {
              #episodeId: episodeId,
            }),
            returnValue: _i9.Future<_i6.PodcastConversationClearResponse>.value(
              _FakePodcastConversationClearResponse_12(
                this,
                Invocation.method(#clearConversationHistory, [], {
                  #episodeId: episodeId,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.PodcastConversationClearResponse>);

  @override
  _i9.Future<_i7.ScheduleConfigResponse> getSubscriptionSchedule(
    int? subscriptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionSchedule, [subscriptionId]),
            returnValue: _i9.Future<_i7.ScheduleConfigResponse>.value(
              _FakeScheduleConfigResponse_13(
                this,
                Invocation.method(#getSubscriptionSchedule, [subscriptionId]),
              ),
            ),
          )
          as _i9.Future<_i7.ScheduleConfigResponse>);

  @override
  _i9.Future<_i7.ScheduleConfigResponse> updateSubscriptionSchedule(
    int? subscriptionId,
    _i7.ScheduleConfigUpdateRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubscriptionSchedule, [
              subscriptionId,
              request,
            ]),
            returnValue: _i9.Future<_i7.ScheduleConfigResponse>.value(
              _FakeScheduleConfigResponse_13(
                this,
                Invocation.method(#updateSubscriptionSchedule, [
                  subscriptionId,
                  request,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.ScheduleConfigResponse>);

  @override
  _i9.Future<List<_i7.ScheduleConfigResponse>> getAllSubscriptionSchedules() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubscriptionSchedules, []),
            returnValue: _i9.Future<List<_i7.ScheduleConfigResponse>>.value(
              <_i7.ScheduleConfigResponse>[],
            ),
          )
          as _i9.Future<List<_i7.ScheduleConfigResponse>>);

  @override
  _i9.Future<List<_i7.ScheduleConfigResponse>> batchUpdateSubscriptionSchedules(
    List<int>? subscriptionIds,
    _i7.ScheduleConfigUpdateRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateSubscriptionSchedules, [
              subscriptionIds,
              request,
            ]),
            returnValue: _i9.Future<List<_i7.ScheduleConfigResponse>>.value(
              <_i7.ScheduleConfigResponse>[],
            ),
          )
          as _i9.Future<List<_i7.ScheduleConfigResponse>>);
}
