import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

import 'package:personal_ai_assistant/features/podcast/data/repositories/podcast_repository.dart';
import 'package:personal_ai_assistant/features/podcast/data/services/podcast_api_service.dart';
import 'package:personal_ai_assistant/features/podcast/presentation/providers/podcast_providers.dart';

// Mock for PodcastRepository
class MockPodcastRepository extends Mock implements PodcastRepository {}

// Mock for PodcastApiService
class MockPodcastApiService extends Mock implements PodcastApiService {}

// Mock for AudioPlayerNotifier
class MockAudioPlayerNotifier extends Mock implements AudioPlayerNotifier {}

// This file should be generated by build_runner but was created manually